# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    high_res_favicon: "/img/logo_miccall.png"
    apple_touch_icon: "/img/logo_miccall.png"
    keywords: Ladeez First Media, Jen Looper, Developer Advocate, Mobile and Web Developer

Intro:
    name: Jen Looper
    slogan: "Developer Advocate | Speaker | Author | Builder of Interesting Things"
    HeadButton: Jen Looper

Nav:
    Home_name: Home
    is_use_categories : false 
    categories_name: Articles
    is_use_archives : true
    archives_name: Blog
    icon:
        github: 
            use: true
            link: https://github.com/jlooper
        Twitter:
            use: true
            link: https://twitter.com/jenlooper
        Facebook:
            use: false
            link: 
        Instagram:
            use: false
            link:
    pages:
        About: 
            link: "/about/"
        Contact :
            link: "/contact/"
        Projects:
            link: "/projects/"
        Speaking:
            link: "/speaking/"
        
MainFirst:
    name: Welcome!
    description: Discover my mobile apps and learn about my other projects.  
    pic_url: ./images/me.jpg
    goto_ulr: "./projects/"

Gallery :
    title: Ladeez First Media 
    description: Projects 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: ladeezfirstmedia

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
